config/routes.rb
Contacts::Application.routes.draw do
  resources :people

  

end

app/models/address.rb
class Address < ActiveRecord::Base
	belongs_to :person
end

app/models/person.rb
class Person < ActiveRecord::Base
	has_one :address

	accepts_nested_attributes_for :address

	def name
		first_name + " " + last_name
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def index
  	@people = Person.all
  end

  def show
  	@person = Person.find(params[:id])
  	@address = @person.address 
  end

  def new
  	@person = Person.new
  	@person.build_address
  end

  def edit
  	@person = Person.find(params[:id])
  end

  def create
  	@person = Person.new(person_params)

  	if @person.save
  		flash[:notice] = "Saved person."
  		redirect_to people_url
  	else
  		render 'new'
  	end
  end

  def update
  	@person = Person.find(params[:id])

  	if @person.update(person_params)
  		flash[:notice] = "Person updated."
  		redirect_to people_url
  	else
  		render 'edit'
  	end
  end

  def destroy
  	@person = Person.find(params[:id])

  	@person.destroy

  	redirect_to people_url
  end


  private
  def person_params
  	params.require(:person).permit(
  			:first_name, :last_name, :phone,
  			address_attributes:
  			[:street_address, :city, :state, :zip] 
  	)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Contacts</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/people/_form.html.erb
<%= form_for @person do |f| %>
<fieldset>
	<legend>Person</legend>
<div>
	<%= f.label :first_name %>
	<%= f.text_field :first_name %>
</div>
<div>
	<%= f.label :last_name %>
	<%= f.text_field :last_name %>
</div>
<div>
	<%= f.label :phone %>
	<%= f.text_field :phone %>
</div>
</fieldset>
<fieldset>
	<legend>Address</legend>
	<%= f.fields_for :address do |address_form| %>
		<div>
			<%= address_form.label :street_address %>
			<%= address_form.text_field :street_address %>
		</div>
		<div>
			<%= address_form.label :city %>
			<%= address_form.text_field :city %>
		</div>
		<div>
			<%= address_form.label :state %>
			<%= address_form.text_field :state %>
		</div>
		<div>
			<%= address_form.label :zip %>
			<%= address_form.text_field :zip %>
		</div>
	<% end %>
</fieldset>
<div>
	<%= f.submit %>
</div>
<% end %>

app/views/people/edit.html.erb
<h1>Edit Person</h1>

<%= render 'form' %>

app/views/people/index.html.erb
<h1>People</h1>

<table>
	<thead>
		<tr>
			<th>Name</th>
			<th>Phone</th>
			<th>City</th>
		</tr>
	</thead>
	<tbody>
	<% @people.each do |person| %>
	<tr>
		<td><%= person.name %></td>
		<td><%= person.phone %></td>
		<td>
				<% if person.address.nil? %>
				No City
				<% else %>
				<%= person.address.city %>
				<% end %> 
		</td>
		<td>
						<%= link_to "Show", person %> |
						<%= link_to "Edit", edit_person_path(person) %> |
						<%= link_to "Delete", person, method: :delete,
																																					confirm: 'Are you sure?' %>
		</td>
	</tr>
	<% end %>
	</tbody>
</table>

<%= link_to "Add person", new_person_path %>

app/views/people/new.html.erb
<h1>New Person</h1>

<%= render 'form' %>

app/views/people/show.html.erb
<h1><%= @person.name %></h1>
<div>
	Phone: <%= @person.phone %>
</div>
<% if @address %>
<div>
	Address: <%= @address.street_address %>
</div>
<div>
	City: <%= @address.city %>
</div>
<div>
	State: <%= @address.state %>
</div>
<div>
	Zip: <%= @address.zip %>
</div>
<% end %>